package edu.illinois.koepcke3.util

import org.bukkit.Material
import org.bukkit.entity.EntityType

object EntityMapper {
    //[print("Pair(EntityType.{}, Material.{}),".format(entity, egg)) for entity, egg in [item.replace("monster_egg","").replace(",","").strip().upper().split(": ") for item in yml.split('\n')]]
    //https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/config/mob_eggs.yml
    val entityToEgg = mapOf(
            Pair(EntityType.BAT, Material.BAT_SPAWN_EGG),
            Pair(EntityType.BEE, Material.BEE_SPAWN_EGG),
            Pair(EntityType.BLAZE, Material.BLAZE_SPAWN_EGG),
            Pair(EntityType.CAT, Material.CAT_SPAWN_EGG),
            Pair(EntityType.CAVE_SPIDER, Material.CAVE_SPIDER_SPAWN_EGG),
            Pair(EntityType.CHICKEN, Material.CHICKEN_SPAWN_EGG),
            Pair(EntityType.COD, Material.COD_SPAWN_EGG),
            Pair(EntityType.COW, Material.COW_SPAWN_EGG),
            Pair(EntityType.CREEPER, Material.CREEPER_SPAWN_EGG),
            Pair(EntityType.DOLPHIN, Material.DOLPHIN_SPAWN_EGG),
            Pair(EntityType.DONKEY, Material.DONKEY_SPAWN_EGG),
            Pair(EntityType.DROWNED, Material.DROWNED_SPAWN_EGG),
            Pair(EntityType.ELDER_GUARDIAN, Material.ELDER_GUARDIAN_SPAWN_EGG),
            Pair(EntityType.ENDERMAN, Material.ENDERMAN_SPAWN_EGG),
            Pair(EntityType.ENDERMITE, Material.ENDERMITE_SPAWN_EGG),
            Pair(EntityType.EVOKER, Material.EVOKER_SPAWN_EGG),
            Pair(EntityType.FOX, Material.FOX_SPAWN_EGG),
            Pair(EntityType.GHAST, Material.GHAST_SPAWN_EGG),
            Pair(EntityType.GUARDIAN, Material.GUARDIAN_SPAWN_EGG),
            Pair(EntityType.HORSE, Material.HORSE_SPAWN_EGG),
            Pair(EntityType.HUSK, Material.HUSK_SPAWN_EGG),
            Pair(EntityType.ILLUSIONER, Material.VINDICATOR_SPAWN_EGG),
            Pair(EntityType.LLAMA, Material.LLAMA_SPAWN_EGG),
            Pair(EntityType.MAGMA_CUBE, Material.MAGMA_CUBE_SPAWN_EGG),
            Pair(EntityType.MUSHROOM_COW, Material.MOOSHROOM_SPAWN_EGG),
            Pair(EntityType.MULE, Material.MULE_SPAWN_EGG),
            Pair(EntityType.OCELOT, Material.OCELOT_SPAWN_EGG),
            Pair(EntityType.PANDA, Material.PANDA_SPAWN_EGG),
            Pair(EntityType.PARROT, Material.PARROT_SPAWN_EGG),
            Pair(EntityType.PHANTOM, Material.PHANTOM_SPAWN_EGG),
            Pair(EntityType.PILLAGER, Material.PILLAGER_SPAWN_EGG),
            Pair(EntityType.PIG, Material.PIG_SPAWN_EGG),
            Pair(EntityType.POLAR_BEAR, Material.POLAR_BEAR_SPAWN_EGG),
            Pair(EntityType.PUFFERFISH, Material.PUFFERFISH_SPAWN_EGG),
            Pair(EntityType.PUFFERFISH, Material.PUFFERFISH_SPAWN_EGG),
            Pair(EntityType.RABBIT, Material.RABBIT_SPAWN_EGG),
            Pair(EntityType.RAVAGER, Material.RAVAGER_SPAWN_EGG),
            Pair(EntityType.SALMON, Material.SALMON_SPAWN_EGG),
            Pair(EntityType.SHEEP, Material.SHEEP_SPAWN_EGG),
            Pair(EntityType.SHULKER, Material.SHULKER_SPAWN_EGG),
            Pair(EntityType.SILVERFISH, Material.SILVERFISH_SPAWN_EGG),
            Pair(EntityType.SKELETON_HORSE, Material.SKELETON_HORSE_SPAWN_EGG),
            Pair(EntityType.SKELETON, Material.SKELETON_SPAWN_EGG),
            Pair(EntityType.SLIME, Material.SLIME_SPAWN_EGG),
            Pair(EntityType.SPIDER, Material.SPIDER_SPAWN_EGG),
            Pair(EntityType.SQUID, Material.SQUID_SPAWN_EGG),
            Pair(EntityType.STRAY, Material.STRAY_SPAWN_EGG),
            Pair(EntityType.TRADER_LLAMA, Material.TRADER_LLAMA_SPAWN_EGG),
            Pair(EntityType.TROPICAL_FISH, Material.TROPICAL_FISH_SPAWN_EGG),
            Pair(EntityType.TURTLE, Material.TURTLE_SPAWN_EGG),
            Pair(EntityType.VEX, Material.VEX_SPAWN_EGG),
            Pair(EntityType.VILLAGER, Material.VILLAGER_SPAWN_EGG),
            Pair(EntityType.VINDICATOR, Material.VINDICATOR_SPAWN_EGG),
            Pair(EntityType.WANDERING_TRADER, Material.WANDERING_TRADER_SPAWN_EGG),
            Pair(EntityType.WITCH, Material.WITCH_SPAWN_EGG),
            Pair(EntityType.WITHER_SKELETON, Material.WITHER_SKELETON_SPAWN_EGG),
            Pair(EntityType.WOLF, Material.WOLF_SPAWN_EGG),
            Pair(EntityType.ZOMBIE_HORSE, Material.ZOMBIE_HORSE_SPAWN_EGG),
            Pair(EntityType.ZOMBIFIED_PIGLIN, Material.ZOMBIFIED_PIGLIN_SPAWN_EGG),
            Pair(EntityType.ZOMBIE, Material.ZOMBIE_SPAWN_EGG),
            Pair(EntityType.ZOMBIE_VILLAGER, Material.ZOMBIE_VILLAGER_SPAWN_EGG)
    )
}